### ISSUE TITLE
Changing the users to only one file

### ISSUE THREAD

**Issue by shunopoli** [GROG/ansible-role-sudo#6] opened 2016-07-06 17:46 UTC
Thanks for creating this it works as intended

How would I go and modify this to change it where it does not create a separate file for all the users and just puts it into a file that I can define. I tried changing the item.name and it will only add one of my users and not loop through them. Not sure what I am doing wrong. Can you assist?

**Comment by groggemans** [comment] 2016-07-06 21:07
This role only works with separate files. This was done by design. (so sudo users can be managed from different roles)

There are two possible way's you can modify the role to use a single file. The first way is to alter the template by adding a loop that adds each user. You should then pass the dictionary to the template (not a single user). The second way is to use the "line in file" feature to make sure the correct lines are in the file, and loop over the users in the playbook (as is done now).

Hope this get's you started. I'll keep the issue open for a while should you have further questions.

**Comment by groggemans** [comment] 2016-07-18 14:02
@shunopoli As there are no further questions I'll close the issue. Feel free to reply/request re-opening if needed!

**Closed as completed by groggemans** 2016-07-18 14:02 UTC
Labels: question
